# Generated by Django 5.1.7 on 2025-03-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_stripe_accounts_users_stripe_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='stripe_accounts',
            new_name='stripe_account',
        ),
    ]
