# Generated by Django 5.1.7 on 2025-03-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_stripe_accounts_users_stripe_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='stripe_customer',
            new_name='stripe_customer_id',
        ),
    ]
