# Generated by Django 5.1.6 on 2025-03-05 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers/')),
                ('total_songs', models.PositiveIntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_artist', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, to='music.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('song_cover_image', models.ImageField(blank=True, null=True, upload_to='songs/covers/')),
                ('duration', models.DurationField()),
                ('category', models.CharField(choices=[('Premium', 'Premium'), ('Free', 'Free')], default='Free', max_length=255)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(upload_to='songs/audios/')),
                ('plays_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.album')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_artists', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(blank=True, to='music.genre')),
            ],
        ),
    ]
