# Generated by Django 5.1.6 on 2025-03-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='albums', to='music.genre'),
        ),
    ]
