# Generated by Django 5.1.6 on 2025-03-07 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_likesong_unlikesong'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_likes', to='music.song'),
        ),
        migrations.AlterField(
            model_name='likesong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unlikesong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_unlikes', to='music.song'),
        ),
        migrations.AlterField(
            model_name='unlikesong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_unlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
