# Generated by Django 5.1.6 on 2025-03-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_dislikes_song_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genres',
        ),
    ]
