# Generated by Django 5.1.6 on 2025-03-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_album_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='category',
        ),
    ]
