# Generated by Django 5.1.6 on 2025-03-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='total_songs',
            field=models.IntegerField(default=0),
        ),
    ]
